### ISSUE TITLE
`cq_showcase.yml` specification

### ISSUE THREAD

**Issue by roipoussiere** [roipoussiere/cadquery-server#46]
A file containing CadQuery project metada could be used by external tools to render a showcase, used to both define model parameters and predefined samples.

This file must be stored as in the same folder of the python modules generating the model and will be typically named `cq_showcase.yml`. Several showcase files can eventually be present in a single repository, for a better project architecture.

Showcase file proposal sample:

```yml
models:
  - module: box
    title: Box
    parameters:
      - var: width
        title: Box width
        min: 2
        max: 10
        step: 0.5
    samples:
      - title: Small box
        parameters:
          width: 2
      - title: Medium box
        parameters:
          width: 5
      - title: Big box
        parameters:
          width: 10

  - module: washer
    title: Washer
    parameters:
      - var: inner_diam
        title: Inner diameter
        min: 1
        max: 10
      - var: outer_diam
        title: Outer diameter
        min: 2
        max: 20
    samples:
      - title: M2
        parameters:
          inner_diam: 2.1
          outer_diam: 6
      - title: M3
        parameters:
          inner_diam: 3.1
          outer_diam: 10
      - title: M4
        parameters:
          inner_diam: 4.1
          outer_diam: 14
```
